version: '3.7'

services:
  postgres:
      image: postgres:16-alpine
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      restart: always
      networks:
        - app-network

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "${APP_PORT}:5000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      API_KEY: ${API_KEY}
      API_USER: ${API_USER}
      API_PASSWORD: ${API_PASSWORD}
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network: